name: deepmower
channels:
  - pytorch
  - defaults
dependencies:
  - _libgcc_mutex=0.1
  - _openmp_mutex=4.5
  - blas=1.0
  - brotli=1.0.9
  - ca-certificates=2021.10.26
  - certifi=2021.10.8
  - cudatoolkit
  - cycler=0.10.0
  - dbus=1.13.18
  - expat=2.4.1
  - fontconfig=2.13.1
  - fonttools=4.25.0
  - freetype=2.11.0
  - giflib=5.2.1
  - glib=2.69.1
  - gst-plugins-base=1.14.0
  - gstreamer=1.14.0
  - icu=58.2
  - intel-openmp=2021.4.0
  - jpeg=9d
  - kiwisolver=1.3.1
  - lcms2=2.12
  - ld_impl_linux-64=2.35.1
  - libffi=3.3
  - libgcc-ng=9.3.0
  - libgomp=9.3.0
  - libpng=1.6.37
  - libstdcxx-ng=9.3.0
  - libtiff=4.2.0
  - libuuid=1.0.3
  - libuv=1.40.0
  - libwebp=1.2.0
  - libwebp-base=1.2.0
  - libxcb=1.14
  - libxml2=2.9.12
  - lz4-c=1.9.3
  - matplotlib=3.4.3
  - matplotlib-base=3.4.3
  - mkl=2021.4.0
  - mkl-service=2.4.0
  - mkl_fft=1.3.1
  - mkl_random=1.2.2
  - munkres=1.1.4
  - ncurses=6.3
  - numpy-base=1.21.2
  - olefile=0.46
  - openssl=1.1.1l
  - pcre=8.45
  - pillow=8.4.0
  - pip=21.2.4
  - pyparsing=3.0.4
  - pyqt=5.9.2
  - python=3.8.12
  - python-dateutil=2.8.2
  - pytorch=1.10.0
  - pytorch-mutex=1.0
  - qt=5.9.7
  - readline=8.1
  - setuptools=58.0.4
  - sip=4.19.13
  - six=1.16.0
  - sqlite=3.36.0
  - tk=8.6.11
  - tornado=6.1
  - typing_extensions=3.10.0.2
  - wheel=0.37.0
  - xz=5.2.5
  - zlib=1.2.11
  - zstd=1.4.9
  - pip:
    - cloudpickle==2.0.0
    - gym==0.21.0
    - gym-retro==0.8.0
    - numpy==1.21.4
    - opencv-python==4.5.4.58
    - pyglet==1.5.21